-- River's own schema (ADR-003), vendored here rather than run via
-- `rivermigrate`'s Go API at deploy time — this keeps a single migration
-- story (`make migrate`, golang-migrate) instead of two competing runners.
-- Generated by running `rivermigrate.Migrate` (all 7 of its own internal
-- versions, main line) against a scratch database and dumping the
-- resulting schema verbatim — this file is not hand-written SQL, it is
-- River v0.43.0's canonical schema, kept in sync by re-generating on
-- upgrade rather than hand-editing.
--
-- `packages/queue` (Go, real inserts via `github.com/riverqueue/river`)
-- and `packages/riverpy` (Python, hand-rolled consumer per ADR-003 — the
-- official `riverqueue` PyPI client is insert-only and cannot run workers)
-- both read/write these tables directly.

CREATE TYPE river_job_state AS ENUM (
    'available',
    'cancelled',
    'completed',
    'discarded',
    'pending',
    'retryable',
    'running',
    'scheduled'
);

CREATE FUNCTION river_job_state_in_bitmask(bitmask BIT, state river_job_state) RETURNS BOOLEAN
    LANGUAGE SQL IMMUTABLE
    AS $$
    SELECT CASE state
        WHEN 'available' THEN get_bit(bitmask, 7)
        WHEN 'cancelled' THEN get_bit(bitmask, 6)
        WHEN 'completed' THEN get_bit(bitmask, 5)
        WHEN 'discarded' THEN get_bit(bitmask, 4)
        WHEN 'pending'   THEN get_bit(bitmask, 3)
        WHEN 'retryable' THEN get_bit(bitmask, 2)
        WHEN 'running'   THEN get_bit(bitmask, 1)
        WHEN 'scheduled' THEN get_bit(bitmask, 0)
        ELSE 0
    END = 1;
$$;

CREATE SEQUENCE river_job_id_seq;

CREATE TABLE river_job (
    id             BIGINT PRIMARY KEY DEFAULT nextval('river_job_id_seq'),
    state          river_job_state NOT NULL DEFAULT 'available',
    attempt        SMALLINT NOT NULL DEFAULT 0,
    max_attempts   SMALLINT NOT NULL DEFAULT 25,
    attempted_at   TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    finalized_at   TIMESTAMPTZ,
    scheduled_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    priority       SMALLINT NOT NULL DEFAULT 1,
    args           JSONB NOT NULL,
    attempted_by   TEXT [],
    errors         JSONB [],
    kind           TEXT NOT NULL,
    metadata       JSONB NOT NULL DEFAULT '{}',
    queue          TEXT NOT NULL DEFAULT 'default',
    tags           VARCHAR(255) [] NOT NULL DEFAULT '{}',
    unique_key     BYTEA,
    unique_states  BIT(8),
    CONSTRAINT finalized_or_finalized_at_null CHECK (
        (finalized_at IS NULL AND state NOT IN ('cancelled', 'completed', 'discarded'))
        OR (finalized_at IS NOT NULL AND state IN ('cancelled', 'completed', 'discarded'))
    ),
    CONSTRAINT kind_length CHECK (char_length(kind) > 0 AND char_length(kind) < 128),
    CONSTRAINT max_attempts_is_positive CHECK (max_attempts > 0),
    CONSTRAINT priority_in_range CHECK (priority >= 1 AND priority <= 4),
    CONSTRAINT queue_length CHECK (char_length(queue) > 0 AND char_length(queue) < 128)
);

ALTER SEQUENCE river_job_id_seq OWNED BY river_job.id;

CREATE INDEX river_job_args_index ON river_job USING gin (args);
CREATE INDEX river_job_kind ON river_job USING btree (kind);
CREATE INDEX river_job_metadata_index ON river_job USING gin (metadata);
CREATE INDEX river_job_prioritized_fetching_index ON river_job USING btree (state, queue, priority, scheduled_at, id);
CREATE INDEX river_job_state_and_finalized_at_index ON river_job USING btree (state, finalized_at)
WHERE finalized_at IS NOT NULL;
CREATE UNIQUE INDEX river_job_unique_idx ON river_job USING btree (unique_key)
WHERE unique_key IS NOT NULL AND unique_states IS NOT NULL
    AND river_job_state_in_bitmask(unique_states, state);

CREATE UNLOGGED TABLE river_leader (
    elected_at  TIMESTAMPTZ NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    leader_id   TEXT NOT NULL,
    name        TEXT NOT NULL DEFAULT 'default',
    CONSTRAINT leader_id_length CHECK (char_length(leader_id) > 0 AND char_length(leader_id) < 128),
    CONSTRAINT name_length CHECK (name = 'default'),
    PRIMARY KEY (name)
);

CREATE TABLE river_migration (
    line        TEXT NOT NULL,
    version     BIGINT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT line_length CHECK (char_length(line) > 0 AND char_length(line) < 128),
    CONSTRAINT version_gte_1 CHECK (version >= 1),
    PRIMARY KEY (line, version)
);

CREATE SEQUENCE river_notification_id_seq;

CREATE TABLE river_notification (
    id          BIGINT PRIMARY KEY DEFAULT nextval('river_notification_id_seq'),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    payload     TEXT NOT NULL,
    topic       TEXT NOT NULL,
    CONSTRAINT topic_length CHECK (length(topic) > 0 AND length(topic) < 128)
);

ALTER SEQUENCE river_notification_id_seq OWNED BY river_notification.id;

CREATE INDEX river_notification_created_at_idx ON river_notification USING btree (created_at);
CREATE INDEX river_notification_topic_id_idx ON river_notification USING btree (topic, id);

CREATE TABLE river_queue (
    name        TEXT NOT NULL PRIMARY KEY,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata    JSONB NOT NULL DEFAULT '{}',
    paused_at   TIMESTAMPTZ,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Records River's own internal migration versions (distinct from this
-- project's golang-migrate version) so `rivermigrate`'s Go API — used only
-- to regenerate this file on a future River upgrade, never at runtime —
-- knows this schema is already fully migrated.
INSERT INTO river_migration (line, version) VALUES
    ('main', 1), ('main', 2), ('main', 3), ('main', 4), ('main', 5), ('main', 6), ('main', 7);
